version: '3'
services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins
    ports:
      - 8080:8080
    volumes:
      - './jenkins_home:/var/jenkins_home'
      - './scripts:/tmp/scripts'

  remote_host:
    container_name: remote_host
    image: remote_host
    build:
      context: agent
    volumes:
      - './scripts:/tmp/scripts'
