version: '3'
services:
  jenkins:
    container_name: jenkins
    image: jenkins-ansible
    build:
      context: jenkins-ansible
    ports:
      - 8080:8080
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - ./scripts:/tmp/scripts
      - ./ansible:/var/jenkins_home/ansible

  remote_host:
    container_name: remote_host
    image: remote_host
    build:
      context: agent
    volumes:
      - './scripts:/tmp/scripts'

  db_host:
    container_name: db_host
    image: mysql:5.7
    environment:
      - "MYSQL_ROOT_PASSWORD=1234"
    volumes:
      - ./db_data:/var/lib/mysql
